# Generated by Django 4.2.6 on 2023-11-20 23:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Tracker', '0002_pmddf_tracker_user_delete_pmdd'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PMDDf',
            new_name='PMDD',
        ),
    ]
