# Generated by Django 4.2.6 on 2023-11-21 01:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tracker', '0004_alter_tracker_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tracker',
            old_name='name',
            new_name='firstname',
        ),
        migrations.RenameField(
            model_name='tracker',
            old_name='anger',
            new_name='irritation',
        ),
        migrations.RenameField(
            model_name='tracker',
            old_name='periodtype',
            new_name='periodflow',
        ),
        migrations.AddField(
            model_name='tracker',
            name='lastname',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
