# Generated by Django 4.2.6 on 2023-11-26 22:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tracker', '0005_rename_name_tracker_firstname_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tracker',
            name='date',
            field=models.DateField(default=datetime.date(2023, 11, 26)),
        ),
    ]
