# Generated by Django 4.2.6 on 2023-12-10 21:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tracker', '0007_rename_name_user_firstname_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tracker',
            name='date',
            field=models.DateField(default=datetime.date(2023, 12, 10)),
        ),
    ]
