# Generated by Django 4.2.6 on 2023-12-11 02:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tracker', '0008_alter_tracker_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tracker',
            name='user',
        ),
        migrations.AddField(
            model_name='tracker',
            name='firstname',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='tracker',
            name='lastname',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
