# Generated by Django 4.2.6 on 2023-12-12 02:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Tracker', '0010_alter_tracker_date'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PMDD',
        ),
    ]
